# Application
spring.application.name=plagiarism1
#
## H2 Database
#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:dcbapp
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=password
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Database (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5433/plagirix_db
spring.datasource.username=admin
spring.datasource.password=Leslie05%
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# File Upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# OpenAI
openai.api.key=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
openai.api.url=https://api.openai.com/v1/chat/completions

# Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=francoise05leslie@gmail.com
spring.mail.password=hjef unrb qace eomo
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# JWT
jwt.encryption.key=7477f0de9d84245e9dbd9cab01ddd403ac70f4ffd57190abf9685d7f34fa6e08
#
#logging.level.org.springframework=DEBUG
#logging.level.org.hibernate=DEBUG

# Ensure proper ID generation
spring.jpa.hibernate.use-new-id-generator-mappings=true

# Disable second-level cache
spring.jpa.properties.hibernate.cache.use_second_level_cache=false
spring.jpa.properties.hibernate.cache.use_query_cache=false

# Show SQL for debugging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

spring.security.oauth2.client.registration.google.client-id=763779973470-a1htisrlcpsqhpph3vaigliulnv67j8m.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google
spring.security.oauth2.client.registration.google.scope=openid,profile,email



spring.security.oauth2.client.registration.github.client-id=Ov23liL8zOmlJGAxw7iw
spring.security.oauth2.client.registration.github.client-secret=665ce87c8de2170fc3ecffca58091a4d2b035f28
spring.security.oauth2.client.registration.github.redirect-uri=http://localhost:8080/login/oauth2/code/google